:embedly_key: ''   # TODO :required:
:canonical_url: '' # TODO :required:
:author_email: ''  # TODO :required:
:author_name: ''   # TODO :required:
:author_uri: ''    # TODO :required'

:shareaholic_key: null      # TODO
:short_url: null            # TODO
:google_analytics_key: null # TODO
:fblike_fragment: null      # TODO
:rss: null                  # TODO

:rate_limit: 60
:image_root: 'http://static.embed.ly/images/kalimba'
:js_root: 'http://static.embed.ly/js/kalimba'
:css_root: 'http://static.embed.ly/css/kalimba'
:tagline: "Embedly Colored Glasses for Hacker News"
:top_comment: true
:hn_root: 'http://news.ycombinator.com'
:shareaholic_plugin: 'http://www.shareaholic.com/media/js/jquery.shareaholic-publishers-api.min.js'
:google_api: 'http://ajax.googleapis.com/ajax/libs'
